### 로그인 실패 테스트
POST http://localhost:8080/login
Content-Type: application/json

{
  "username" : "user01",
  "password" : "pass01"
}

### 로그인 성공 테스트
POST http://localhost:8080/login
Content-Type: application/json

{
  "username" : "user01",
  "password" : "1234"
}

### 인증 실패 테스트
POST http://localhost:8080/posts

### 인증 성공 테스트
POST http://localhost:8080/posts
Authorization: Bearer eyJkYXRlIjoxNzE2MTExMDc0NDM0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsInVzZXJuYW1lIjoidXNlcjAxIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxNjExNDY3NH0.sV46SCY9C8R8aeHIQpf6RghOkkcoqIchYrl3fsusiMh4lchrr44dWFVcYLgAZt8siKqwwU7anLip3dH2IuRb8w

### 인가 실패 테스트
POST http://localhost:8080/categories
Authorization: Bearer eyJkYXRlIjoxNzE2MTExMDc0NDM0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsInVzZXJuYW1lIjoidXNlcjAxIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxNjExNDY3NH0.sV46SCY9C8R8aeHIQpf6RghOkkcoqIchYrl3fsusiMh4lchrr44dWFVcYLgAZt8siKqwwU7anLip3dH2IuRb8w